### ISSUE TITLE
Feature request: change the text when succeeding/failing

### ISSUE THREAD

**Issue by mawrkus** [enemycnt/mico-spinner#17]
Hi,
Thank you for your code!
I wanted to switch from ora to your library but I have a use case where I'd like to print a different text when the spinner stops (e.g. duration in ms).
Would you consider adding a "text" parameter to "stopAndPrint"?
Would you accept a PR?
m

**Comment by usmanyunusov** [comment]
@mawrkus https://github.com/usmanyunusov/nanospinner will help you
